import type { Metadata } from "next";
import { Jost } from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const jost = Jost({
  subsets: ['latin', 'latin-ext', 'cyrillic'],
  weight: ["400", "500", "600", "700"]
})


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased flex justify-center w-full ${jost.className}`}
      >
        <div className="w-full max-w-[2560px]">{children}</div>
      </body>
    </html>
  );
}
